/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root liveness check
         * @description Unversioned system path: GET /
         */
        get: operations["AppController_getRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active categories */
        get: operations["CatalogsController_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active districts */
        get: operations["CatalogsController_districts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Unversioned system path: GET /health/live
         */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Unversioned system path: GET /health/ready
         */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CategoryDto: {
            /**
             * @description Opaque string identifier (UUID v4)
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Display name
             * @example Gasfiteria y tuberias
             */
            name: string;
            /**
             * @description URL-safe slug preserving original casing semantics
             * @example gasfiteria-y-tuberias
             */
            slug: string;
        };
        CategoryEnvelopeDto: {
            /** @description Data envelope {data:[...]} */
            data: {
                /**
                 * @description Opaque string identifier (UUID v4)
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
                /**
                 * @description Display name
                 * @example Gasfiteria y tuberias
                 */
                name: string;
                /**
                 * @description URL-safe slug preserving original casing semantics
                 * @example gasfiteria-y-tuberias
                 */
                slug: string;
            }[];
        };
        DistrictDto: {
            /**
             * @description Department name
             * @example Lima
             */
            department: string;
            /**
             * @description Opaque string identifier (UUID v4)
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description District name
             * @example Lima
             */
            name: string;
            /**
             * @description Province name
             * @example Lima
             */
            province: string;
            /**
             * @description Ubigeo code (6-digit)
             * @example 150101
             */
            ubigeoCode: string;
        };
        DistrictEnvelopeDto: {
            /** @description Data envelope {data:[...]} */
            data: {
                /**
                 * @description Department name
                 * @example Lima
                 */
                department: string;
                /**
                 * @description Opaque string identifier (UUID v4)
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
                /**
                 * @description District name
                 * @example Lima
                 */
                name: string;
                /**
                 * @description Province name
                 * @example Lima
                 */
                province: string;
                /**
                 * @description Ubigeo code (6-digit)
                 * @example 150101
                 */
                ubigeoCode: string;
            }[];
        };
        MoneyDto: {
            /**
             * @description Decimal amount as string (two fractional digits)
             * @example 125.50
             */
            amount: string;
            /**
             * @description ISO 4217 currency code
             * @example PEN
             * @enum {string}
             */
            currency: "PEN";
        };
        PaginationQueryDto: {
            /**
             * @description Items per page (reusable pagination component)
             * @example 20
             */
            limit?: number;
            /**
             * @description Page number, 1-based (reusable pagination component)
             * @example 1
             */
            page?: number;
        };
        ProblemDetailsDto: {
            /**
             * @description Stable error code (9 values)
             * @example INPUT_INVALID
             * @enum {string}
             */
            code: "INPUT_INVALID" | "AUTHENTICATION_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "SEMANTIC_INVALID" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
            /**
             * @description Detailed explanation
             * @example The request input is invalid.
             */
            detail: string;
            /** @description Optional field-level errors keyed by field path */
            fieldErrors?: {
                [key: string]: string[];
            };
            /**
             * @description HTTP status code
             * @example 400
             */
            status: number;
            /**
             * @description Short human-readable summary
             * @example Input Invalid
             */
            title: string;
            /**
             * @description Correlation trace ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            traceId: string;
            /**
             * @description RFC 7807 type URI (urn:reparared:error:{CODE})
             * @example urn:reparared:error:INPUT_INVALID
             */
            type: string;
        };
        SystemStatusDto: {
            /** @example ok */
            status: string;
        };
        TimestampDto: {
            /**
             * Format: date-time
             * @description RFC 3339 timestamp
             * @example 2026-01-15T12:30:00.000Z
             */
            value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
            /** @description Route not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Stable error code (9 values)
                         * @example INPUT_INVALID
                         * @enum {string}
                         */
                        code: "INPUT_INVALID" | "AUTHENTICATION_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "SEMANTIC_INVALID" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
                        /**
                         * @description Detailed explanation
                         * @example The request input is invalid.
                         */
                        detail: string;
                        /** @description Optional field-level errors keyed by field path */
                        fieldErrors?: {
                            [key: string]: string[];
                        };
                        /**
                         * @description HTTP status code
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description Short human-readable summary
                         * @example Input Invalid
                         */
                        title: string;
                        /**
                         * @description Correlation trace ID
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        traceId: string;
                        /**
                         * @description RFC 7807 type URI (urn:reparared:error:{CODE})
                         * @example urn:reparared:error:INPUT_INVALID
                         */
                        type: string;
                    };
                };
            };
        };
    };
    CatalogsController_categories: {
        parameters: {
            query?: {
                /** @description active=true accepted; active=false -> 422; malformed -> 400 */
                active?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Data envelope {data:[...]} */
                        data: {
                            /**
                             * @description Opaque string identifier (UUID v4)
                             * @example 550e8400-e29b-41d4-a716-446655440000
                             */
                            id: string;
                            /**
                             * @description Display name
                             * @example Gasfiteria y tuberias
                             */
                            name: string;
                            /**
                             * @description URL-safe slug preserving original casing semantics
                             * @example gasfiteria-y-tuberias
                             */
                            slug: string;
                        }[];
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Stable error code (9 values)
                         * @example INPUT_INVALID
                         * @enum {string}
                         */
                        code: "INPUT_INVALID" | "AUTHENTICATION_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "SEMANTIC_INVALID" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
                        /**
                         * @description Detailed explanation
                         * @example The request input is invalid.
                         */
                        detail: string;
                        /** @description Optional field-level errors keyed by field path */
                        fieldErrors?: {
                            [key: string]: string[];
                        };
                        /**
                         * @description HTTP status code
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description Short human-readable summary
                         * @example Input Invalid
                         */
                        title: string;
                        /**
                         * @description Correlation trace ID
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        traceId: string;
                        /**
                         * @description RFC 7807 type URI (urn:reparared:error:{CODE})
                         * @example urn:reparared:error:INPUT_INVALID
                         */
                        type: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Stable error code (9 values)
                         * @example INPUT_INVALID
                         * @enum {string}
                         */
                        code: "INPUT_INVALID" | "AUTHENTICATION_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "SEMANTIC_INVALID" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
                        /**
                         * @description Detailed explanation
                         * @example The request input is invalid.
                         */
                        detail: string;
                        /** @description Optional field-level errors keyed by field path */
                        fieldErrors?: {
                            [key: string]: string[];
                        };
                        /**
                         * @description HTTP status code
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description Short human-readable summary
                         * @example Input Invalid
                         */
                        title: string;
                        /**
                         * @description Correlation trace ID
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        traceId: string;
                        /**
                         * @description RFC 7807 type URI (urn:reparared:error:{CODE})
                         * @example urn:reparared:error:INPUT_INVALID
                         */
                        type: string;
                    };
                };
            };
        };
    };
    CatalogsController_districts: {
        parameters: {
            query?: {
                /** @description active=true accepted; active=false -> 422; malformed -> 400 */
                active?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Data envelope {data:[...]} */
                        data: {
                            /**
                             * @description Department name
                             * @example Lima
                             */
                            department: string;
                            /**
                             * @description Opaque string identifier (UUID v4)
                             * @example 550e8400-e29b-41d4-a716-446655440000
                             */
                            id: string;
                            /**
                             * @description District name
                             * @example Lima
                             */
                            name: string;
                            /**
                             * @description Province name
                             * @example Lima
                             */
                            province: string;
                            /**
                             * @description Ubigeo code (6-digit)
                             * @example 150101
                             */
                            ubigeoCode: string;
                        }[];
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Stable error code (9 values)
                         * @example INPUT_INVALID
                         * @enum {string}
                         */
                        code: "INPUT_INVALID" | "AUTHENTICATION_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "SEMANTIC_INVALID" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
                        /**
                         * @description Detailed explanation
                         * @example The request input is invalid.
                         */
                        detail: string;
                        /** @description Optional field-level errors keyed by field path */
                        fieldErrors?: {
                            [key: string]: string[];
                        };
                        /**
                         * @description HTTP status code
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description Short human-readable summary
                         * @example Input Invalid
                         */
                        title: string;
                        /**
                         * @description Correlation trace ID
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        traceId: string;
                        /**
                         * @description RFC 7807 type URI (urn:reparared:error:{CODE})
                         * @example urn:reparared:error:INPUT_INVALID
                         */
                        type: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Stable error code (9 values)
                         * @example INPUT_INVALID
                         * @enum {string}
                         */
                        code: "INPUT_INVALID" | "AUTHENTICATION_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "SEMANTIC_INVALID" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
                        /**
                         * @description Detailed explanation
                         * @example The request input is invalid.
                         */
                        detail: string;
                        /** @description Optional field-level errors keyed by field path */
                        fieldErrors?: {
                            [key: string]: string[];
                        };
                        /**
                         * @description HTTP status code
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description Short human-readable summary
                         * @example Input Invalid
                         */
                        title: string;
                        /**
                         * @description Correlation trace ID
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        traceId: string;
                        /**
                         * @description RFC 7807 type URI (urn:reparared:error:{CODE})
                         * @example urn:reparared:error:INPUT_INVALID
                         */
                        type: string;
                    };
                };
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Stable error code (9 values)
                         * @example INPUT_INVALID
                         * @enum {string}
                         */
                        code: "INPUT_INVALID" | "AUTHENTICATION_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "SEMANTIC_INVALID" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
                        /**
                         * @description Detailed explanation
                         * @example The request input is invalid.
                         */
                        detail: string;
                        /** @description Optional field-level errors keyed by field path */
                        fieldErrors?: {
                            [key: string]: string[];
                        };
                        /**
                         * @description HTTP status code
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description Short human-readable summary
                         * @example Input Invalid
                         */
                        title: string;
                        /**
                         * @description Correlation trace ID
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        traceId: string;
                        /**
                         * @description RFC 7807 type URI (urn:reparared:error:{CODE})
                         * @example urn:reparared:error:INPUT_INVALID
                         */
                        type: string;
                    };
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
            /** @description Service not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Stable error code (9 values)
                         * @example INPUT_INVALID
                         * @enum {string}
                         */
                        code: "INPUT_INVALID" | "AUTHENTICATION_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "SEMANTIC_INVALID" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
                        /**
                         * @description Detailed explanation
                         * @example The request input is invalid.
                         */
                        detail: string;
                        /** @description Optional field-level errors keyed by field path */
                        fieldErrors?: {
                            [key: string]: string[];
                        };
                        /**
                         * @description HTTP status code
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description Short human-readable summary
                         * @example Input Invalid
                         */
                        title: string;
                        /**
                         * @description Correlation trace ID
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        traceId: string;
                        /**
                         * @description RFC 7807 type URI (urn:reparared:error:{CODE})
                         * @example urn:reparared:error:INPUT_INVALID
                         */
                        type: string;
                    };
                };
            };
        };
    };
}
